name: Download Coqui XTTS Model
on: [workflow_dispatch] # Se activa manualmente desde la pesta√±a Actions

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Download XTTS v2
        run: |
          python -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='coqui/XTTS-v2', local_dir='xtts_v2', allow_patterns=['*.pth', '*.json', '*.csv', '*.txt'])"
      
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xtts-v2-model
          path: xtts_v2/
