name: Exportar Motor Fish Speech
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Imagen Base Oficial
        run: |
          # Probamos con la etiqueta más genérica y estable
          docker pull fishaudio/fish-speech:latest
          # La renombramos para que tu docker-compose no se confunda
          docker tag fishaudio/fish-speech:latest fish-motor:ready

      - name: Guardar en TAR
        run: |
          docker save fish-motor:ready -o fish_engine.tar

      - name: Subir Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: motor-docker-fish
          path: fish_engine.tar
          retention-days: 1:
